#cifar_naive.py

import numpy as np
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model, Input
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D

VERBOSE = False
adam = keras.optimizers.Adam(lr=0.0001)

def layer1(epochs):
    batch_size = 32
    num_classes = 10
    data_augmentation = True

    # The data, shuffled and split between train and test sets:
    (x_train, y_train), (x_test, y_test) = cifar10.load_data()
    if VERBOSE:
        print('x_train shape:', x_train.shape)
        print(x_train.shape[0], 'train samples')
        print(x_test.shape[0], 'test samples')

    # Convert class vectors to binary class matrices.
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    main_input = Input(shape=x_train.shape[1:], name='main_input')
    conv1 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv1')(main_input)
    conv1 = Dropout(0.3)(conv1) ####
    conv1_flat = Flatten()(conv1)
    fc1 = Dense(512, activation='relu', name='fc1')(conv1_flat)
    fc1_drop = Dropout(0.5)(fc1)
    main_output = Dense(10, activation='softmax', name='fc2')(fc1_drop)

    model = Model(inputs=[main_input], outputs=[main_output])
    model.compile(optimizer=adam,
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 255
    x_test /= 255

    if not data_augmentation:
        if VERBOSE: print('Not using data augmentation.')
        model.fit(x_train, y_train,
                  batch_size=batch_size,
                  epochs=epochs,
                  validation_data=(x_test, y_test),
                  shuffle=True)
    else:
        if VERBOSE: print('Using real-time data augmentation.')
        # This will do preprocessing and realtime data augmentation:
        datagen = ImageDataGenerator(
            featurewise_center=False,  # set input mean to 0 over the dataset
            samplewise_center=False,  # set each sample mean to 0
            featurewise_std_normalization=False,  # divide inputs by std of the dataset
            samplewise_std_normalization=False,  # divide each input by its std
            zca_whitening=False,  # apply ZCA whitening
            rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
            width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
            height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
            horizontal_flip=True,  # randomly flip images
            vertical_flip=False)  # randomly flip images

        # Compute quantities required for feature-wise normalization
        # (std, mean, and principal components if ZCA whitening is applied).
        datagen.fit(x_train)

        # Fit the model on the batches generated by datagen.flow().
        history = model.fit_generator(datagen.flow(x_train, y_train,
                                         batch_size=batch_size),
                            steps_per_epoch=x_train.shape[0] // batch_size,
                            epochs=epochs,
                            validation_data=(x_test, y_test))

    np.savez('layer1_results.npz', acc=history.history['acc'], loss=history.history['loss'],
              val_acc=history.history['val_acc'], val_loss=history.history['val_loss'])

    conv1_weights = model.get_layer('conv1').get_weights()
    return conv1_weights

def layer2(epochs, conv1_weights):
    batch_size = 32
    num_classes = 10
    data_augmentation = True

    # The data, shuffled and split between train and test sets:
    (x_train, y_train), (x_test, y_test) = cifar10.load_data()
    if VERBOSE:
        print('x_train shape:', x_train.shape)
        print(x_train.shape[0], 'train samples')
        print(x_test.shape[0], 'test samples')

    # Convert class vectors to binary class matrices.
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    main_input = Input(shape=x_train.shape[1:], name='main_input')
    conv1 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv1',
                   trainable=False)(main_input)
    conv2 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv2')(conv1)
    conv2 = Dropout(.3)(conv2) #####
    conv2_flat = Flatten()(conv2)

    fc1 = Dense(512, activation='relu', name='fc1')(conv2_flat)
    fc1_drop = Dropout(0.5)(fc1)
    main_output = Dense(10, activation='softmax', name='fc2')(fc1_drop)

    model = Model(inputs=[main_input], outputs=[main_output])
    model.compile(optimizer=adam,
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    model.get_layer('conv1').set_weights(conv1_weights)

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 255
    x_test /= 255

    if not data_augmentation:
        if VERBOSE: print('Not using data augmentation.')
        model.fit(x_train, y_train,
                  batch_size=batch_size,
                  epochs=epochs,
                  validation_data=(x_test, y_test),
                  shuffle=True)
    else:
        if VERBOSE: print('Using real-time data augmentation.')
        # This will do preprocessing and realtime data augmentation:
        datagen = ImageDataGenerator(
            featurewise_center=False,  # set input mean to 0 over the dataset
            samplewise_center=False,  # set each sample mean to 0
            featurewise_std_normalization=False,  # divide inputs by std of the dataset
            samplewise_std_normalization=False,  # divide each input by its std
            zca_whitening=False,  # apply ZCA whitening
            rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
            width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
            height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
            horizontal_flip=True,  # randomly flip images
            vertical_flip=False)  # randomly flip images

        # Compute quantities required for feature-wise normalization
        # (std, mean, and principal components if ZCA whitening is applied).
        datagen.fit(x_train)

        # Fit the model on the batches generated by datagen.flow().
        history = model.fit_generator(datagen.flow(x_train, y_train,
                                         batch_size=batch_size),
                            steps_per_epoch=x_train.shape[0] // batch_size,
                            epochs=epochs,
                            validation_data=(x_test, y_test))

    np.savez('layer2_results.npz', acc=history.history['acc'], loss=history.history['loss'],
              val_acc=history.history['val_acc'], val_loss=history.history['val_loss'])

    conv2_weights = model.get_layer('conv2').get_weights()
    return conv2_weights

def layer3(epochs, conv1_weights, conv2_weights):
    batch_size = 32
    num_classes = 10
    data_augmentation = True

    # The data, shuffled and split between train and test sets:
    (x_train, y_train), (x_test, y_test) = cifar10.load_data()
    if VERBOSE:
        print('x_train shape:', x_train.shape)
        print(x_train.shape[0], 'train samples')
        print(x_test.shape[0], 'test samples')

    # Convert class vectors to binary class matrices.
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    main_input = Input(shape=x_train.shape[1:], name='main_input')
    conv1 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv1',
                   trainable=False)(main_input)
    conv2 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv2',
                   trainable=False)(conv1)
    conv2_pool = MaxPooling2D(pool_size=(2,2))(conv2)
    conv2_drop = Dropout(.3)(conv2_pool)
    conv3 = Conv2D(64, (3,3),
		   activation='relu',
                   padding='same',
                   name='conv3')(conv2_drop)
    conv3 = Dropout(.3)(conv3) ####
    conv3_flat = Flatten()(conv3)

    fc1 = Dense(512, activation='relu', name='fc1')(conv3_flat)
    fc1_drop = Dropout(0.5)(fc1)
    main_output = Dense(10, activation='softmax', name='fc2')(fc1_drop)

    model = Model(inputs=[main_input], outputs=[main_output])
    model.compile(optimizer=adam,
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    model.get_layer('conv1').set_weights(conv1_weights)
    model.get_layer('conv2').set_weights(conv2_weights)

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 255
    x_test /= 255

    if not data_augmentation:
        if VERBOSE: print('Not using data augmentation.')
        model.fit(x_train, y_train,
                  batch_size=batch_size,
                  epochs=epochs,
                  validation_data=(x_test, y_test),
                  shuffle=True)
    else:
        if VERBOSE: print('Using real-time data augmentation.')
        # This will do preprocessing and realtime data augmentation:
        datagen = ImageDataGenerator(
            featurewise_center=False,  # set input mean to 0 over the dataset
            samplewise_center=False,  # set each sample mean to 0
            featurewise_std_normalization=False,  # divide inputs by std of the dataset
            samplewise_std_normalization=False,  # divide each input by its std
            zca_whitening=False,  # apply ZCA whitening
            rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
            width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
            height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
            horizontal_flip=True,  # randomly flip images
            vertical_flip=False)  # randomly flip images

        # Compute quantities required for feature-wise normalization
        # (std, mean, and principal components if ZCA whitening is applied).
        datagen.fit(x_train)

        # Fit the model on the batches generated by datagen.flow().
        history = model.fit_generator(datagen.flow(x_train, y_train,
                                         batch_size=batch_size),
                            steps_per_epoch=x_train.shape[0] // batch_size,
                            epochs=epochs,
                            validation_data=(x_test, y_test))

    np.savez('layer3_results.npz', acc=history.history['acc'], loss=history.history['loss'],
              val_acc=history.history['val_acc'], val_loss=history.history['val_loss'])

    conv3_weights = model.get_layer('conv3').get_weights()
    return conv3_weights

def layer4(epochs, conv1_weights, conv2_weights, conv3_weights):
    batch_size = 32
    num_classes = 10
    data_augmentation = True

    # The data, shuffled and split between train and test sets:
    (x_train, y_train), (x_test, y_test) = cifar10.load_data()
    if VERBOSE:
        print('x_train shape:', x_train.shape)
        print(x_train.shape[0], 'train samples')
        print(x_test.shape[0], 'test samples')

    # Convert class vectors to binary class matrices.
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    main_input = Input(shape=x_train.shape[1:], name='main_input')
    conv1 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv1',
                   trainable=False)(main_input)
    conv2 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv2',
                   trainable=False)(conv1)
    conv2_pool = MaxPooling2D(pool_size=(2,2))(conv2)
    conv3 = Conv2D(64, (3,3),
		   activation='relu',
                   padding='same',
                   trainable=False,
                   name='conv3')(conv2_pool)
    conv4 = Conv2D(64, (3,3),
                   activation='relu',
		   padding='same',
                   name='conv4')(conv3)
    conv4 = Dropout(.3)(conv4)
    conv4_flat = Flatten()(conv4)

    fc1 = Dense(512, activation='relu', name='fc1')(conv4_flat)
    fc1_drop = Dropout(0.5)(fc1)
    main_output = Dense(10, activation='softmax', name='fc2')(fc1_drop)

    model = Model(inputs=[main_input], outputs=[main_output])
    model.compile(optimizer=adam,
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    model.get_layer('conv1').set_weights(conv1_weights)
    model.get_layer('conv2').set_weights(conv2_weights)
    model.get_layer('conv3').set_weights(conv3_weights)

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 255
    x_test /= 255

    if not data_augmentation:
        if VERBOSE: print('Not using data augmentation.')
        model.fit(x_train, y_train,
                  batch_size=batch_size,
                  epochs=epochs,
                  validation_data=(x_test, y_test),
                  shuffle=True)
    else:
        if VERBOSE: print('Using real-time data augmentation.')
        # This will do preprocessing and realtime data augmentation:
        datagen = ImageDataGenerator(
            featurewise_center=False,  # set input mean to 0 over the dataset
            samplewise_center=False,  # set each sample mean to 0
            featurewise_std_normalization=False,  # divide inputs by std of the dataset
            samplewise_std_normalization=False,  # divide each input by its std
            zca_whitening=False,  # apply ZCA whitening
            rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
            width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
            height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
            horizontal_flip=True,  # randomly flip images
            vertical_flip=False)  # randomly flip images

        # Compute quantities required for feature-wise normalization
        # (std, mean, and principal components if ZCA whitening is applied).
        datagen.fit(x_train)

        # Fit the model on the batches generated by datagen.flow().
        history = model.fit_generator(datagen.flow(x_train, y_train,
                                         batch_size=batch_size),
                            steps_per_epoch=x_train.shape[0] // batch_size,
                            epochs=epochs,
                            validation_data=(x_test, y_test))

    np.savez('layer4_results.npz', acc=history.history['acc'], loss=history.history['loss'],
              val_acc=history.history['val_acc'], val_loss=history.history['val_loss'])

    conv4_weights = model.get_layer('conv4').get_weights()
    return conv4_weights


def layer5(epochs, conv1_weights, conv2_weights, conv3_weights, conv4_weights):
    batch_size = 32
    num_classes = 10
    data_augmentation = True

    # The data, shuffled and split between train and test sets:
    (x_train, y_train), (x_test, y_test) = cifar10.load_data()
    if VERBOSE:
        print('x_train shape:', x_train.shape)
        print(x_train.shape[0], 'train samples')
        print(x_test.shape[0], 'test samples')

    # Convert class vectors to binary class matrices.
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    main_input = Input(shape=x_train.shape[1:], name='main_input')
    conv1 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv1',
                   trainable=False)(main_input)
    conv2 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv2',
                   trainable=False)(conv1)
    conv2_pool = MaxPooling2D(pool_size=(2,2))(conv2)
    conv3 = Conv2D(64, (3,3),
		   activation='relu',
                   padding='same',
                   trainable=False,
                   name='conv3')(conv2_pool)
    conv4 = Conv2D(64, (3,3),
                   activation='relu',
		   padding='same',
                   name='conv4',
                   trainable=False)(conv3)
    conv4_pool = MaxPooling2D(pool_size=(2,2))(conv4)
    conv4_drop = Dropout(.3)(conv4_pool)

    conv5 = Conv2D(128, (3,3),
                   activation='relu',
		   padding='same',
                   name='conv5')(conv4_drop)
    conv5 = Dropout(.3)(conv5)
    conv5_flat = Flatten()(conv5)

    fc1 = Dense(512, activation='relu', name='fc1')(conv5_flat)
    fc1_drop = Dropout(0.5)(fc1)
    main_output = Dense(10, activation='softmax', name='fc2')(fc1_drop)

    model = Model(inputs=[main_input], outputs=[main_output])
    model.compile(optimizer=adam,
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    model.get_layer('conv1').set_weights(conv1_weights)
    model.get_layer('conv2').set_weights(conv2_weights)
    model.get_layer('conv3').set_weights(conv3_weights)
    model.get_layer('conv4').set_weights(conv4_weights)

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 255
    x_test /= 255

    if not data_augmentation:
        if VERBOSE: print('Not using data augmentation.')
        model.fit(x_train, y_train,
                  batch_size=batch_size,
                  epochs=epochs,
                  validation_data=(x_test, y_test),
                  shuffle=True)
    else:
        if VERBOSE: print('Using real-time data augmentation.')
        # This will do preprocessing and realtime data augmentation:
        datagen = ImageDataGenerator(
            featurewise_center=False,  # set input mean to 0 over the dataset
            samplewise_center=False,  # set each sample mean to 0
            featurewise_std_normalization=False,  # divide inputs by std of the dataset
            samplewise_std_normalization=False,  # divide each input by its std
            zca_whitening=False,  # apply ZCA whitening
            rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
            width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
            height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
            horizontal_flip=True,  # randomly flip images
            vertical_flip=False)  # randomly flip images

        # Compute quantities required for feature-wise normalization
        # (std, mean, and principal components if ZCA whitening is applied).
        datagen.fit(x_train)

        # Fit the model on the batches generated by datagen.flow().
        history = model.fit_generator(datagen.flow(x_train, y_train,
                                         batch_size=batch_size),
                            steps_per_epoch=x_train.shape[0] // batch_size,
                            epochs=epochs,
                            validation_data=(x_test, y_test))

    np.savez('layer5_results.npz', acc=history.history['acc'], loss=history.history['loss'],
              val_acc=history.history['val_acc'], val_loss=history.history['val_loss'])

    conv5_weights = model.get_layer('conv5').get_weights()
    return conv5_weights

def layer6(epochs, conv1_weights, conv2_weights, conv3_weights, conv4_weights, conv5_weights):
    batch_size = 32
    num_classes = 10
    data_augmentation = True

    # The data, shuffled and split between train and test sets:
    (x_train, y_train), (x_test, y_test) = cifar10.load_data()
    if VERBOSE:
        print('x_train shape:', x_train.shape)
        print(x_train.shape[0], 'train samples')
        print(x_test.shape[0], 'test samples')

    # Convert class vectors to binary class matrices.
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    main_input = Input(shape=x_train.shape[1:], name='main_input')
    conv1 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv1',
                   trainable=False)(main_input)
    conv2 = Conv2D(32, (3,3),
                   activation='relu',
                   padding='same',
                   name='conv2',
                   trainable=False)(conv1)
    conv2_pool = MaxPooling2D(pool_size=(2,2))(conv2)
    conv3 = Conv2D(64, (3,3),
		   activation='relu',
                   padding='same',
                   trainable=False,
                   name='conv3')(conv2_pool)
    conv4 = Conv2D(64, (3,3),
                   activation='relu',
		   padding='same',
                   name='conv4',
                   trainable=False)(conv3)
    conv4_pool = MaxPooling2D(pool_size=(2,2))(conv4)

    conv5 = Conv2D(128, (3,3),
                   activation='relu',
		   padding='same',
                   name='conv5',
                   trainable=False)(conv4_pool)
    conv6 = Conv2D(128, (3,3),
                   activation='relu',
		   padding='same',
                   name='conv6')(conv5)
    conv6 = Dropout(.3)(conv6)
    conv6_flat = Flatten()(conv6)

    fc1 = Dense(512, activation='relu', name='fc1')(conv6_flat)
    fc1_drop = Dropout(0.5)(fc1)
    main_output = Dense(10, activation='softmax', name='fc2')(fc1_drop)

    model = Model(inputs=[main_input], outputs=[main_output])
    model.compile(optimizer=adam,
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    model.get_layer('conv1').set_weights(conv1_weights)
    model.get_layer('conv2').set_weights(conv2_weights)
    model.get_layer('conv3').set_weights(conv3_weights)
    model.get_layer('conv4').set_weights(conv4_weights)
    model.get_layer('conv5').set_weights(conv5_weights)


    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 255
    x_test /= 255

    if not data_augmentation:
        if VERBOSE: print('Not using data augmentation.')
        model.fit(x_train, y_train,
                  batch_size=batch_size,
                  epochs=epochs,
                  validation_data=(x_test, y_test),
                  shuffle=True)
    else:
        if VERBOSE: print('Using real-time data augmentation.')
        # This will do preprocessing and realtime data augmentation:
        datagen = ImageDataGenerator(
            featurewise_center=False,  # set input mean to 0 over the dataset
            samplewise_center=False,  # set each sample mean to 0
            featurewise_std_normalization=False,  # divide inputs by std of the dataset
            samplewise_std_normalization=False,  # divide each input by its std
            zca_whitening=False,  # apply ZCA whitening
            rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
            width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
            height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
            horizontal_flip=True,  # randomly flip images
            vertical_flip=False)  # randomly flip images

        # Compute quantities required for feature-wise normalization
        # (std, mean, and principal components if ZCA whitening is applied).
        datagen.fit(x_train)

        # Fit the model on the batches generated by datagen.flow().
        history = model.fit_generator(datagen.flow(x_train, y_train,
                                         batch_size=batch_size),
                            steps_per_epoch=x_train.shape[0] // batch_size,
                            epochs=epochs,
                            validation_data=(x_test, y_test))

    np.savez('layer6_results.npz', acc=history.history['acc'], loss=history.history['loss'],
              val_acc=history.history['val_acc'], val_loss=history.history['val_loss'])

    conv5_weights = model.get_layer('conv5').get_weights()
    return conv5_weights





import numpy as np

print "LAYER 1"
conv1_weights = layer1(50) #20
np.savez('conv1_weightsnpz', W=conv1_weights[0], b=conv1_weights[1])

print "LAYER 2"
conv2_weights = layer2(50, conv1_weights) #40
np.savez('conv2_weights.npz', W=conv2_weights[0], b=conv2_weights[1])

#conv1_weights = np.load('conv1_weights.npz')
#conv1_weights = [conv1_weights['W'], conv1_weights['b']]

#conv2_weights = np.load('conv2_weights.npz')
#conv2_weights = [conv2_weights['W'], conv2_weights['b']]

print "LAYER 3"
conv3_weights = layer3(75, conv1_weights, conv2_weights) #100
np.savez('conv3_weights.npz', W=conv3_weights[0], b=conv3_weights[1])

#conv3_weights = np.load('conv3_weights.npz')
#conv3_weights = [conv3_weights['W'], conv3_weights['b']]

print "LAYER 4"
conv4_weights = layer4(75, conv1_weights, conv2_weights, conv3_weights) #100
np.savez('conv4_weights.npz', W=conv4_weights[0], b=conv4_weights[1])

#conv4_weights = np.load('conv4_weights.npz')
#conv4_weights = [conv4_weights['W'], conv4_weights['b']]

print "LAYER 5"
conv5_weights = layer5(100, conv1_weights, conv2_weights, conv3_weights, conv4_weights) #100
np.savez('conv5_weights.npz', W=conv5_weights[0], b=conv5_weights[1])

print "LAYER 6"
conv6_weights = layer6(100, conv1_weights, conv2_weights, conv3_weights, conv4_weights, conv5_weights) #140
np.savez('conv6_weights.npz', W=conv6_weights[0], b=conv6_weights[1])
